import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { publicAddressDisplay, publicPhoneDisplay, publicPhoneHref } from "@/lib/contact";
import { whatsappUrl } from "@/lib/whatsapp";
import { TechnicalVisual } from "@/components/TechnicalVisual";

export const metadata=routeMetadata("/contacto", "Contacto y cotizaciones", "Contacta a RINON para evaluar fabricación metálica, estructuras, cierres, camarotes y proyectos a medida.");

export default function Page(){
  const whatsapp=whatsappUrl(); const phone=publicPhoneHref();
  return <main className="v5-editorial-page">
    <section className="v2-solution-hero"><div className="container v2-solution-hero-grid"><div><div className="v2-eyebrow">CONTACTO · SAN BERNARDO</div><h1>Hablemos con el contexto correcto.</h1><p>Para cotizar una fabricación, una foto, plano, croquis, cantidad o medida aproximada suele ahorrar más tiempo que un mensaje genérico.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="contact_hero" href="/cotizar">Iniciar cotización</Link>{whatsapp?<a className="v2-btn outline" data-event="contact_whatsapp" data-cta-location="contact_hero" href={whatsapp} target="_blank" rel="noopener noreferrer">Hablar por WhatsApp</a>:null}</div><div className="v2-kickers"><span>Taller / atención en San Bernardo</span><span>Empresas y particulares</span><span>Proyectos y compras por volumen</span></div></div><TechnicalVisual kind="fabrication" label={publicAddressDisplay()} detail="San Bernardo · Región Metropolitana" /></div></section>
    <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ELIGE EL CAMINO</div><h2>No todas las consultas necesitan el mismo nivel de detalle.</h2></div><p>Parte por el canal que mejor representa tu requerimiento. Puedes cambiar de ruta durante la evaluación.</p></div><div className="v2-contact-paths"><Link href="/cotizar"><span>01 · PROYECTO</span><h3>Tengo una idea, plano, foto o medidas.</h3><p>Usa la cotización guiada para ordenar antecedentes y reducir supuestos.</p><b>Iniciar cotización →</b></Link><Link href="/cotizar?client=b2b"><span>02 · EMPRESA</span><h3>Necesito comprar por volumen o fabricar bajo requerimiento.</h3><p>Parte con cantidad, destino, fecha objetivo y modalidad de compra.</p><b>Flujo para empresas →</b></Link>{whatsapp?<a href={whatsapp} target="_blank" rel="noopener noreferrer"><span>03 · CONVERSACIÓN</span><h3>Necesito aclarar primero si RINON puede evaluar esto.</h3><p>WhatsApp sirve como entrada rápida cuando todavía no tienes el requerimiento ordenado.</p><b>Abrir WhatsApp →</b></a>:<Link href="/cotizar"><span>03 · CONSULTA</span><h3>Todavía no tengo el requerimiento completo.</h3><p>Envía lo que ya sabes y separaremos lo confirmado de lo que falta definir.</p><b>Empezar con lo disponible →</b></Link>}</div></div></section>
    <section className="v2-solution-section"><div className="container"><div className="v2-contact-grid"><article><span>WHATSAPP</span><h2>Conversemos directo.</h2>{whatsapp?<a href={whatsapp} target="_blank" rel="noopener noreferrer">{publicPhoneDisplay()} →</a>:null}</article><article><span>TELÉFONO</span><h2>Contacto comercial.</h2>{phone?<a href={phone}>{publicPhoneDisplay()} →</a>:null}</article><article><span>TALLER</span><h2>San Bernardo.</h2><p>{publicAddressDisplay()}<br/>Región Metropolitana</p></article></div></div></section>
    <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ANTES DE ESCRIBIR</div><h2>Qué antecedentes ayudan a avanzar.</h2></div><p>No todos aplican a todos los proyectos. Envía lo que tengas y completa el resto durante la evaluación.</p></div><div className="card-grid"><article><span>01</span><h3>Qué necesitas</h3><p>Producto, estructura, cierre o descripción del problema.</p></article><article><span>02</span><h3>Medidas o referencia</h3><p>Plano, foto, croquis o dimensiones aproximadas.</p></article><article><span>03</span><h3>Cantidad</h3><p>Una unidad, lote o volumen estimado.</p></article><article><span>04</span><h3>Ubicación</h3><p>Comuna o región para evaluar logística cuando corresponda.</p></article></div></div></section>
  </main>;
}
