import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { TechnicalVisual } from "@/components/TechnicalVisual";

export const metadata=routeMetadata(
  "/mallas-3d",
  "Malla 3D y panel electrosoldado para cierres perimetrales",
  "Paneles de malla electrosoldada para evaluar dentro de cierres perimetrales. Configuración, altura, postes, terminación e instalación se confirman al cotizar.",
);

export default function Page(){return <main className="v5-editorial-page theme-product">
  <section className="v2-solution-hero"><div className="container v2-solution-hero-grid"><div><div className="v2-eyebrow">MALLA 3D · PANEL ELECTROSOLDADO</div><h1>Un panel metálico modular para el perímetro.</h1><p>La malla 3D corresponde a la familia de paneles electrosoldados utilizados en cierres perimetrales. Antes de cotizar se confirman dimensiones, altura, postes, terminación, accesos y condiciones del terreno.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="malla3d_hero" href="/cotizar?category=cierres&detail=malla_3d">Cotizar malla 3D</Link><Link className="v2-btn outline" href="/cierres-perimetrales">Comparar cierres</Link></div><div className="v2-kickers"><span>Panel electrosoldado</span><span>Postes</span><span>Altura</span><span>Metros lineales</span></div></div><TechnicalVisual kind="fence" label="Panel, postes y encuentros." detail="Metros · altura · terreno · accesos · terminación" /></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">QUÉ SE DEFINE</div><h2>El panel es solo una parte del cierre.</h2></div><p>Para comparar correctamente una solución de malla electrosoldada hay que considerar también postes, fijaciones, encuentros, puertas o portones y la condición donde se instalará.</p></div><div className="card-grid"><article><span>01</span><h3>Panel</h3><p>La geometría, terminación y configuración vigente se expresan en la cotización aplicable al proyecto.</p></article><article><span>02</span><h3>Postes y fijación</h3><p>Se revisan según el recorrido, soporte disponible y alcance de instalación.</p></article><article><span>03</span><h3>Encuentros</h3><p>Esquinas, cambios de nivel y uniones con muros o accesos deben aparecer en el requerimiento.</p></article><article><span>04</span><h3>Accesos</h3><p>Puertas y portones se coordinan como parte del sistema cuando corresponda.</p></article></div></div></section>

  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">PARA COTIZAR</div><h2>Parte por el perímetro, no por una ficha genérica.</h2></div><p>Metros, altura, terreno y accesos permiten saber si esta familia de paneles tiene sentido para el proyecto antes de cerrar una especificación.</p></div><div className="v2-step-grid"><article><span>01 · METROS</span><h3>Largo del cierre</h3><p>Metros lineales aproximados y forma del perímetro.</p></article><article><span>02 · ALTURA</span><h3>Altura requerida</h3><p>Indica la altura objetivo o la restricción existente.</p></article><article><span>03 · TERRENO</span><h3>Condición de instalación</h3><p>Fotos, pendientes, muros, radieres u otros apoyos existentes.</p></article><article><span>04 · ACCESOS</span><h3>Puertas y portones</h3><p>Cantidad, ancho aproximado y tipo de tránsito que deben permitir.</p></article></div></div></section>

  <section className="v2-capabilities"><div className="container v2-capabilities-grid"><div><div className="v2-eyebrow">SIN SOBREESPECIFICAR</div><h2>La cotización manda sobre la referencia web.</h2><p>No publicamos una única medida, calibre, resistencia o terminación como si aplicara a todos los proyectos. La configuración vigente y el alcance concreto quedan expresados antes de fabricar o suministrar.</p></div><div className="v2-capability-list"><div><span>01</span><strong>Metraje</strong><em>ESCALA</em></div><div><span>02</span><strong>Altura</strong><em>GEOMETRÍA</em></div><div><span>03</span><strong>Postes</strong><em>SISTEMA</em></div><div><span>04</span><strong>Accesos</strong><em>INTEGRACIÓN</em></div><div><span>05</span><strong>Terminación</strong><em>ALCANCE</em></div></div></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ALTERNATIVAS</div><h2>Compara por función y contexto.</h2></div><p>Si todavía no decidiste el tipo de cierre, revisa la familia completa antes de fijar material o geometría.</p></div><div className="v2-resource-grid"><Link href="/cierres-perimetrales"><span>GUÍA DE FAMILIA</span><h3>Cierres perimetrales</h3><p>Compara sistemas según uso, visibilidad, terreno y accesos.</p><b>Ver cierres →</b></Link><Link href="/rejas-metalicas"><span>REJA</span><h3>Rejas metálicas</h3><p>Alternativa fabricada según vanos, tramos y configuración del proyecto.</p><b>Ver rejas →</b></Link><Link href="/recursos/tipos-de-cierres-perimetrales"><span>RECURSO</span><h3>Tipos de cierres perimetrales</h3><p>Qué variables conviene comparar antes de pedir precio.</p><b>Leer guía →</b></Link></div></div></section>

  <section className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">TU PERÍMETRO</div><h2>¿Quieres evaluar panel electrosoldado?</h2><p>Envía metros lineales, altura, ubicación y fotografías del terreno.</p></div><Link className="v2-btn orange" href="/cotizar?category=cierres&detail=malla_3d">Cotizar malla 3D</Link></div></section>
</main>}
