import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { TechnicalVisual } from "@/components/TechnicalVisual";
import { VisualEvidence } from "@/components/VisualEvidence";

export const metadata=routeMetadata("/proyectos","Proyectos y evidencia RINON","Biblioteca de evidencia y proyectos RINON. Los casos se publican únicamente cuando su procedencia está verificada.",{indexable:false});

export default function Page(){return <main className="v5-editorial-page">
  <section className="v2-solution-hero"><div className="container v2-solution-hero-grid"><div><div className="v2-eyebrow">PROYECTOS Y EVIDENCIA</div><h1>Evidencia que se puede explicar.</h1><p>La biblioteca reúne evidencia de producto y, cuando corresponde, casos documentados con contexto suficiente para entender el requerimiento, el alcance y el resultado.</p></div><TechnicalVisual kind="structure" label="Evidencia verificable." detail="Requerimiento · proceso · escala · resultado" /></div></section>
  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ESTÁNDAR DE CASO</div><h2>La evidencia útil muestra contexto además del resultado.</h2></div><p>Cada caso documentado debe ayudar a entender qué se pidió, cómo se abordó la fabricación y qué resultado puede compararse con un nuevo requerimiento.</p></div><div className="card-grid"><article><span>01</span><h3>Requerimiento</h3><p>Qué problema debía resolver, para qué uso y bajo qué restricciones.</p></article><article><span>02</span><h3>Fabricación</h3><p>Proceso y decisiones que puedan comunicarse con respaldo.</p></article><article><span>03</span><h3>Escala</h3><p>Cantidad, metraje o dimensión contextual cuando sea publicable.</p></article><article><span>04</span><h3>Resultado</h3><p>Producto o instalación terminada sin atribuciones no validadas.</p></article></div></div></section>
  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">REFERENCIAS ACTUALES</div><h2>Producto real como punto de referencia.</h2></div><p>Las imágenes de producto ayudan a conversar sobre configuración, construcción y escala. Un cliente o proyecto se identifica solo cuando existe respaldo suficiente para hacerlo.</p></div><div className="v2-evidence-layout"><VisualEvidence slug="/camarotes" fallback={["producto completo","detalle constructivo","cantidad","contexto"]}/><div className="v2-evidence-copy"><span>REGLA DE PROCEDENCIA</span><h3>La evidencia comercial debe poder defenderse.</h3><p>Cuando un caso incluye nombre, ubicación o cliente, esos antecedentes se validan antes de publicarlo.</p><ul><li>Qué se fabricó</li><li>Qué alcance tuvo RINON</li><li>Qué dato puede publicarse</li><li>Qué imagen corresponde realmente</li></ul></div></div></div></section>
  <section className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">TU PROYECTO</div><h2>¿Necesitas una solución similar?</h2><p>Describe el requerimiento; no necesitas esperar a que exista un caso idéntico.</p></div><div className="v2-final-actions"><Link className="v2-btn orange" href="/cotizar">Cotizar proyecto</Link><Link className="v2-btn outline" href="/fabricacion-metalica">Ver fabricación</Link></div></div></section>
</main>}
