import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { publicAddressDisplay } from "@/lib/contact";
import { TechnicalVisual } from "@/components/TechnicalVisual";

export const metadata=routeMetadata("/nosotros","RINON Soluciones Metálicas","RINON fabrica soluciones metálicas desde San Bernardo para particulares, empresas e instituciones.");

export default function Page(){return <main className="v5-editorial-page">
  <section className="v2-solution-hero"><div className="container v2-solution-hero-grid"><div><div className="v2-eyebrow">RINON · SOLUCIONES METÁLICAS</div><h1>Fabricación directa. Alcance claro.</h1><p>RINON funciona como fabricante y solucionador metalmecánico: productos conocidos cuando existe una configuración vigente y fabricación a medida cuando el requerimiento necesita otra respuesta.</p><div className="v2-kickers"><span>{publicAddressDisplay()}</span><span>Particulares</span><span>Empresas</span><span>Instituciones</span></div></div><TechnicalVisual kind="structure" label="Demostrar antes de prometer." detail="Fabricación · precisión · respuesta · evidencia" /></div></section>
  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">CÓMO PENSAMOS</div><h2>La confianza se construye con alcance y evidencia.</h2></div><p>Preferimos definir qué incluye cada trabajo antes de prometer. Lo estándar se identifica, lo especial se evalúa y cualquier condición variable queda aclarada en la cotización.</p></div><div className="metric-strip"><div><b>Productos</b><span>Camas, camarotes y equipamiento cuando existe una configuración evaluable.</span></div><div><b>Perímetros</b><span>Cierres, rejas y portones según lugar y uso.</span></div><div><b>Estructuras</b><span>Soportes, bastidores, escaleras y soluciones de habilitación.</span></div><div><b>Especiales</b><span>Piezas y conjuntos desde plano, muestra, foto, croquis o medidas.</span></div></div></div></section>
  <section className="v2-capabilities"><div className="container v2-capabilities-grid"><div><div className="v2-eyebrow">TALLER</div><h2>Capacidades de fabricación en taller.</h2><p>Corte, dimensionado, doblado, soldadura MIG, armado y fabricación por unidad o volumen dentro de la factibilidad del trabajo.</p></div><div className="v2-capability-list"><div><span>01</span><strong>Acero estructural</strong><em>MATERIAL</em></div><div><span>02</span><strong>Acero inoxidable</strong><em>MATERIAL</em></div><div><span>03</span><strong>Aluminio estructural</strong><em>MATERIAL</em></div><div><span>04</span><strong>Soldadura MIG y armado</strong><em>PROCESO</em></div></div></div></section>
  <section className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">SIGUIENTE PASO</div><h2>¿Tienes una idea, plano o referencia?</h2><p>Envíala junto con cantidad y ubicación. Si faltan datos, pediremos solo los relevantes.</p></div><div className="v2-final-actions"><Link className="v2-btn orange" href="/cotizar">Iniciar cotización</Link><Link className="v2-btn outline" href="/contacto">Contacto y ubicación</Link></div></div></section>
</main>}
