import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { WhatsAppCTA } from "@/components/WhatsAppCTA";

export const metadata=routeMetadata("/empresas","Fabricación metálica para empresas e instituciones","Fabricación metálica para compras por volumen, proyectos, obras e instituciones con evaluación de cantidad, alcance, logística y fecha objetivo.");

const buyers=[
  ["COMPRAS", "Necesita comparar alcance y precio", "Cantidad, especificación, destino, fecha y condiciones comerciales claramente separadas."],
  ["OPERACIONES", "Necesita resolver una función", "Uso real, restricciones, ubicación, mantenimiento y continuidad operacional."],
  ["OBRA / TERRENO", "Necesita coordinar fabricación y montaje", "Medidas, accesos, secuencia, interferencias y condiciones del sitio."],
  ["ADMINISTRACIÓN", "Necesita trazabilidad del requerimiento", "Qué se pidió, qué se cotizó, qué cambió y qué incluye finalmente el alcance."],
] as const;

const proof=[
 ["VOLUMEN","Series, lotes y compras repetibles cuando cantidad y configuración están definidas."],
 ["BAJO PLANO","Piezas, soportes y conjuntos cuando la geometría y especificación vienen definidas."],
 ["PROYECTO","Cierres, estructuras y equipamiento asociados a una obra o necesidad de terreno."],
 ["RECURRÍNTE","Requerimientos que se repiten y pueden estandarizarse comercialmente."],
] as const;

export default function Page(){return <main className="v5-editorial-page rinon-enterprise-page">
  <section className="v2-solution-hero rinon-enterprise-hero"><div className="container rinon-enterprise-hero-grid"><div><div className="v2-eyebrow">EMPRESAS · INSTITUCIONES · OBRAS</div><h1>Fabricación para empresas, obras e instituciones.</h1><p>Desde una serie de camarotes hasta cierres, estructuras, soportes o piezas bajo plano. Cuéntanos cantidad, destino y fecha objetivo para ordenar la evaluación desde el inicio.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="b2b_hero" href="/cotizar?client=b2b">Cotizar para empresa</Link><WhatsAppCTA location="b2b_hero" label="Conversar por WhatsApp" className="v2-btn outline" /></div><div className="v2-kickers"><span>Compra por volumen</span><span>Proyecto / obra</span><span>Bajo plano</span><span>Requerimiento recurrente</span></div></div><aside className="rinon-proof-panel" aria-label="Modalidades de fabricación para empresas"><span>QUÉ PODEMOS ORDENAR CONTIGO</span>{proof.map(([title,body],index)=><div key={title}><b>0{index+1}</b><strong>{title}</strong><p>{body}</p></div>)}<small>La capacidad, plazo y alcance final se confirman para cada cotización.</small></aside></div></section>

  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">QUIÉN NECESITA QUÉ</div><h2>Un mismo proyecto se ve distinto según el rol.</h2></div><p>La solicitud comercial debe recoger suficiente contexto para que el requerimiento sobreviva al traspaso entre áreas.</p></div><div className="card-grid">{buyers.map(([tag,title,body])=><article key={tag}><span>{tag}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ENTORNOS DE COMPRA</div><h2>Lo que se fabrica cambia según la operación.</h2></div><p>La misma capacidad de taller puede resolver necesidades distintas. Lo importante es definir uso, cantidad, destino y condiciones del proyecto.</p></div><div className="v2-sector-grid"><article><span>01</span><h3>Construcción y obra</h3><p>Cierres, estructuras, soportes, accesos y piezas asociadas a una habilitación o frente de trabajo.</p><small>CLAVE · medidas · secuencia · terreno</small></article><article><span>02</span><h3>Industria y mantenimiento</h3><p>Reparaciones, bases, protecciones, bastidores y fabricaciones para resolver una necesidad operacional concreta.</p><small>CLAVE · función · interferencias · continuidad</small></article><article><span>03</span><h3>Bodegas y logística</h3><p>Equipamiento, divisiones, cierres y elementos repetibles para ordenar o habilitar espacios.</p><small>CLAVE · uso · espacio · cantidad</small></article><article><span>04</span><h3>Instituciones y faenas</h3><p>Camas, camarotes, lockers y otros productos cuando cantidad, destino y entrega son parte central de la compra.</p><small>CLAVE · volumen · destino · fecha</small></article></div></div></section>

  <section className="v2-capabilities"><div className="container v2-capabilities-grid"><div><div className="v2-eyebrow">CÓMO AVANZA</div><h2>Una compra ordenada desde el primer contacto.</h2><p>Primero entendemos lo que se necesita. Después definimos qué falta confirmar para convertirlo en una propuesta fabricable y coordinable.</p></div><div className="v2-capability-list"><div><span>01</span><strong>Necesidad</strong><em>CONTEXTO</em></div><div><span>02</span><strong>Revisión</strong><em>FACTIBILIDAD</em></div><div><span>03</span><strong>Cotización</strong><em>ALCANCE</em></div><div><span>04</span><strong>Coordinación</strong><em>PROYECTO</em></div><div><span>05</span><strong>Fabricación y entrega</strong><em>EJECUCIÓN</em></div></div></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">PARA UNA PRIMERA REVISIÓN</div><h2>Cuatro datos permiten empezar.</h2></div><p>No necesitas preparar una licitación completa para conversar. Con estos antecedentes podemos identificar rápidamente qué falta.</p></div><div className="v2-step-grid"><article><span>01 · REFERENCIA</span><h3>Qué necesitas</h3><p>Producto, plano, fotografía, muestra o descripción funcional.</p></article><article><span>02 · CANTIDAD</span><h3>Qué volumen</h3><p>Unidades o metraje aproximado para dimensionar fabricación.</p></article><article><span>03 · DESTINO</span><h3>Dónde se entrega</h3><p>Ubicación para evaluar logística y montaje cuando corresponda.</p></article><article><span>04 · FECHA</span><h3>Cuándo lo necesitas</h3><p>Plazo objetivo sujeto a revisión contra alcance y capacidad.</p></article></div></div></section>

  <section className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">EMPRESAS</div><h2>¿Tienes un requerimiento por volumen?</h2><p>Indica cantidad, referencia, destino y fecha objetivo para empezar.</p></div><div className="v2-final-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="b2b_footer" href="/cotizar?client=b2b">Enviar requerimiento B2B</Link><Link className="v2-btn outline" href="/recursos/fabricacion-por-lote-que-definir">Preparar compra</Link></div></div></section>
</main>}
