import Link from "next/link";
import { routeMetadata } from "@/lib/seo";
import { WhatsAppCTA } from "@/components/WhatsAppCTA";
import { TechnicalVisual } from "@/components/TechnicalVisual";

export const metadata=routeMetadata("/empresas","Fabricación metálica para empresas e instituciones","Fabricación metálica para compras por volumen, proyectos, obras e instituciones con evaluación de cantidad, alcance, logística y fecha objetivo.");

const buyers=[
  ["COMPRAS", "Necesita comparar alcance y precio", "Cantidad, especificación, destino, fecha y condiciones comerciales claramente separadas."],
  ["OPERACIONES", "Necesita resolver una función", "Uso real, restricciones, ubicación, mantenimiento y continuidad operacional."],
  ["OBRA / TERRENO", "Necesita coordinar fabricación y montaje", "Medidas, accesos, secuencia, interferencias y condiciones del sitio."],
  ["ADMINISTRACIÓN", "Necesita trazabilidad del requerimiento", "Qué se pidió, qué se cotizó, qué cambió y qué incluye finalmente el alcance."],
] as const;

export default function Page(){return <main className="v5-editorial-page">
  <section className="v2-solution-hero"><div className="container v2-solution-hero-grid"><div><div className="v2-eyebrow">EMPRESAS · INSTITUCIONES · PROYECTOS</div><h1>Fabricación metálica para empresas.</h1><p>Para compras por volumen, proyectos y requerimientos recurrentes, ordenamos cantidad, especificación, destino, fecha objetivo y alcance antes de fabricar.</p><div className="v2-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="b2b_hero" href="/cotizar?client=b2b">Cotizar para empresa</Link><WhatsAppCTA location="b2b_hero" label="Conversar por WhatsApp" className="v2-btn outline" /></div><div className="v2-kickers"><span>Compra por volumen</span><span>Proyecto / obra</span><span>Fabricación bajo plano</span><span>Requerimiento recurrente</span></div></div><TechnicalVisual kind="equipment" label="REQUERIMIENTO B2B" detail="Cantidad · especificación · destino · fecha · alcance" /></div></section>

  <section className="v2-solution-section soft"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">QUIÉN NECESITA QUÉ</div><h2>Un mismo proyecto se ve distinto según el rol.</h2></div><p>La solicitud comercial debe recoger suficiente contexto para que el requerimiento sobreviva al traspaso entre áreas.</p></div><div className="card-grid">{buyers.map(([tag,title,body])=><article key={tag}><span>{tag}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">MODALIDADES</div><h2>Cuatro tipos de demanda que conviene separar.</h2></div><p>Separarlas mejora la cotización, el seguimiento y la medición comercial.</p></div><div className="metric-strip"><div><b>Volumen</b><span>Muchas unidades de una referencia con repetibilidad y logística.</span></div><div><b>Proyecto</b><span>Fabricación asociada a obra, habilitación o una necesidad de terreno.</span></div><div><b>Bajo plano</b><span>Piezas o conjuntos donde geometría y especificación mandan.</span></div><div><b>Recurrente</b><span>Necesidades que se repiten y pueden estandarizarse comercialmente.</span></div></div></div></section>

  <section className="v2-solution-section v2-sector-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">ENTORNOS DE COMPRA</div><h2>La misma capacidad de taller se compra por motivos distintos.</h2></div><p>Ordenamos el requerimiento según el entorno para entender qué antecedente, coordinación y nivel de repetición necesita cada compra.</p></div><div className="v2-sector-grid"><article><span>01</span><h3>Construcción y obra</h3><p>Cierres, estructuras, soportes, accesos y piezas asociadas a una habilitación o frente de trabajo.</p><small>CLAVE · medidas · secuencia · terreno</small></article><article><span>02</span><h3>Industria y mantenimiento</h3><p>Reparaciones, bases, protecciones, bastidores y fabricaciones para resolver una necesidad operacional concreta.</p><small>CLAVE · función · interferencias · continuidad</small></article><article><span>03</span><h3>Bodegas y logística</h3><p>Equipamiento, divisiones, cierres y elementos repetibles para ordenar o habilitar espacios.</p><small>CLAVE · uso · espacio · cantidad</small></article><article><span>04</span><h3>Instituciones y faenas</h3><p>Camas, camarotes, lockers y otros productos/equipamientos cuando la cantidad y la entrega forman parte central de la compra.</p><small>CLAVE · volumen · destino · fecha</small></article></div></div></section>

  <section className="v2-capabilities"><div className="container v2-capabilities-grid"><div><div className="v2-eyebrow">DESDE EL REQUERIMIENTO</div><h2>Una compra ordenada desde el primer contacto.</h2><p>Cantidad, especificación y condiciones quedan claras antes de fabricar, para que compras, operaciones y terreno trabajen sobre el mismo alcance.</p></div><div className="v2-capability-list"><div><span>01</span><strong>Requerimiento</strong><em>CONTEXTO</em></div><div><span>02</span><strong>Revisión técnica</strong><em>FACTIBILIDAD</em></div><div><span>03</span><strong>Alcance y cotización</strong><em>PROPUESTA</em></div><div><span>04</span><strong>Coordinación</strong><em>PROYECTO</em></div><div><span>05</span><strong>Fabricación y entrega</strong><em>EJECUCIÓN</em></div></div></div></section>

  <section className="v2-solution-section"><div className="container"><div className="section-head"><div><div className="v2-eyebrow">PARA UNA PRIMERA REVISIÓN</div><h2>No necesitas preparar una licitación completa.</h2></div><p>Con cantidad, referencia, ubicación y fecha objetivo podemos identificar qué falta antes de convertir el requerimiento en una cotización formal.</p></div><div className="v2-step-grid"><article><span>01 · REFERENCIA</span><h3>Qué necesitas</h3><p>Producto, plano, fotografía, muestra o descripción funcional.</p></article><article><span>02 · CANTIDAD</span><h3>Qué volumen</h3><p>Unidades o metraje aproximado para dimensionar fabricación.</p></article><article><span>03 · DESTINO</span><h3>Dónde se entrega</h3><p>Ubicación para evaluar logística y montaje cuando corresponda.</p></article><article><span>04 · FECHA</span><h3>Cuándo lo necesitas</h3><p>Plazo objetivo sujeto a revisión contra alcance y capacidad.</p></article></div></div></section>

  <section className="v2-final-cta"><div className="container"><div><div className="v2-eyebrow">EMPRESAS</div><h2>¿Necesitas fabricar por volumen?</h2><p>Indica cantidad, antecedentes y fecha objetivo para empezar.</p></div><div className="v2-final-actions"><Link className="v2-btn orange" data-event="quote_start" data-cta-location="b2b_footer" href="/cotizar?client=b2b">Enviar requerimiento B2B</Link><Link className="v2-btn outline" href="/recursos/fabricacion-por-lote-que-definir">Preparar compra</Link></div></div></section>
</main>}
